/* Auto-generated by genmsg_cpp for file /home/rosdev/fuerte_workspace/sandbox/tum_simulator/cvg_sim_msgs/msg/RawImu.msg */
#ifndef CVG_SIM_MSGS_MESSAGE_RAWIMU_H
#define CVG_SIM_MSGS_MESSAGE_RAWIMU_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace cvg_sim_msgs
{
template <class ContainerAllocator>
struct RawImu_ {
  typedef RawImu_<ContainerAllocator> Type;

  RawImu_()
  : header()
  , angular_velocity()
  , linear_acceleration()
  {
    angular_velocity.assign(0);
    linear_acceleration.assign(0);
  }

  RawImu_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , angular_velocity()
  , linear_acceleration()
  {
    angular_velocity.assign(0);
    linear_acceleration.assign(0);
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef boost::array<uint16_t, 3>  _angular_velocity_type;
  boost::array<uint16_t, 3>  angular_velocity;

  typedef boost::array<uint16_t, 3>  _linear_acceleration_type;
  boost::array<uint16_t, 3>  linear_acceleration;


  typedef boost::shared_ptr< ::cvg_sim_msgs::RawImu_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cvg_sim_msgs::RawImu_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct RawImu
typedef  ::cvg_sim_msgs::RawImu_<std::allocator<void> > RawImu;

typedef boost::shared_ptr< ::cvg_sim_msgs::RawImu> RawImuPtr;
typedef boost::shared_ptr< ::cvg_sim_msgs::RawImu const> RawImuConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cvg_sim_msgs::RawImu_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cvg_sim_msgs::RawImu_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cvg_sim_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cvg_sim_msgs::RawImu_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cvg_sim_msgs::RawImu_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cvg_sim_msgs::RawImu_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0879a838e899792bcf72ccfe7b5595ef";
  }

  static const char* value(const  ::cvg_sim_msgs::RawImu_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0879a838e899792bULL;
  static const uint64_t static_value2 = 0xcf72ccfe7b5595efULL;
};

template<class ContainerAllocator>
struct DataType< ::cvg_sim_msgs::RawImu_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cvg_sim_msgs/RawImu";
  }

  static const char* value(const  ::cvg_sim_msgs::RawImu_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cvg_sim_msgs::RawImu_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
uint16[3] angular_velocity\n\
uint16[3] linear_acceleration\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::cvg_sim_msgs::RawImu_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::cvg_sim_msgs::RawImu_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::cvg_sim_msgs::RawImu_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cvg_sim_msgs::RawImu_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.angular_velocity);
    stream.next(m.linear_acceleration);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RawImu_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cvg_sim_msgs::RawImu_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cvg_sim_msgs::RawImu_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "angular_velocity[]" << std::endl;
    for (size_t i = 0; i < v.angular_velocity.size(); ++i)
    {
      s << indent << "  angular_velocity[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.angular_velocity[i]);
    }
    s << indent << "linear_acceleration[]" << std::endl;
    for (size_t i = 0; i < v.linear_acceleration.size(); ++i)
    {
      s << indent << "  linear_acceleration[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.linear_acceleration[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // CVG_SIM_MSGS_MESSAGE_RAWIMU_H

